//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CHEKMAIL.RC
//
#define IDD_DIALOG_MAIN                 101
#define IDC_EDIT1                       1000
#define IDC_SERVERNAME                  1001
#define IDC_USERID                      1002
#define IDC_PASSWORD                    1003
#define ID_CHECKMAIL                    1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
